[package]
authors = [
  "Sam Crow <samcrow@uw.edu>",
  "Sašo Kiselkov <saso@hotstart.net>",
  "pcaracal",
]
name = "xplm-egui"
version = "0.5.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/pcaracal/xplm-egui"
keywords = ["X-Plane", "plugin", "egui"]
description = "High-level interfaces to the X-Plane plugin SDK, plus egui"
readme = "README.md"
edition = "2024"

[dependencies]
xplm-sys = { git = "https://github.com/pcaracal/xplm-sys.git" }
bytemuck = "1.25.0"
egui = { version = "0.34.1", features = ["bytemuck"] }
euclid = "0.22.14"
gl_loader = "0.1.2"
glow = "0.17.0"
memoffset = "0.9.1"
num = { version = "0.4.3" }
pastey = "0.2.2"
thiserror = "2.0.18"
uom = { version = "0.38.0" }
anyhow = "1.0.102"
bitflags = "2.11.1"
egui_extras = "0.34.1"

[dev-dependencies]
derive_more = { version = "2.1.1", features = ["try_from"] }
simplelog = "0.12.2"
log = "0.4.29"

[profile.release]
opt-level = 3
lto = true
incremental = true
codegen-units = 1
strip = "symbols"

[[example]]
name = "egui"
crate-type = ["cdylib"]

[[example]]
name = "egui_datarefs"
crate-type = ["cdylib"]

[[example]]
name = "minimal"
crate-type = ["cdylib"]

[[example]]
name = "dataref"
crate-type = ["cdylib"]

[[example]]
name = "menus"
crate-type = ["cdylib"]
